/*
 * This file is generated by jOOQ.
 */
package com.epam.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product implements Serializable {

    private static final long serialVersionUID = -421834826;

    private final Integer    id;
    private final Object     name;
    private final BigDecimal price;
    private final Integer    categoryId;
    private final Object     vendor;
    private final Object     sn;
    private final Object     owner;

    public Product(Product value) {
        this.id = value.id;
        this.name = value.name;
        this.price = value.price;
        this.categoryId = value.categoryId;
        this.vendor = value.vendor;
        this.sn = value.sn;
        this.owner = value.owner;
    }

    public Product(
        Integer    id,
        Object     name,
        BigDecimal price,
        Integer    categoryId,
        Object     vendor,
        Object     sn,
        Object     owner
    ) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.categoryId = categoryId;
        this.vendor = vendor;
        this.sn = sn;
        this.owner = owner;
    }

    public Integer getId() {
        return this.id;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getName() {
        return this.name;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getVendor() {
        return this.vendor;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getSn() {
        return this.sn;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getOwner() {
        return this.owner;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Product (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(price);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(vendor);
        sb.append(", ").append(sn);
        sb.append(", ").append(owner);

        sb.append(")");
        return sb.toString();
    }
}
