/*
 * This file is generated by jOOQ.
 */
package org.jooq.epam.contest.public_.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Description implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long    id;
    private final Integer productId;
    private final Integer descr;

    public Description(Description value) {
        this.id = value.id;
        this.productId = value.productId;
        this.descr = value.descr;
    }

    public Description(
        Long    id,
        Integer productId,
        Integer descr
    ) {
        this.id = id;
        this.productId = productId;
        this.descr = descr;
    }

    /**
     * Getter for <code>public.description.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.description.product_id</code>.
     */
    public Integer getProductId() {
        return this.productId;
    }

    /**
     * Getter for <code>public.description.descr</code>.
     */
    public Integer getDescr() {
        return this.descr;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Description (");

        sb.append(id);
        sb.append(", ").append(productId);
        sb.append(", ").append(descr);

        sb.append(")");
        return sb.toString();
    }
}
