/*
 * This file is generated by jOOQ.
 */
package org.jooq.epam.contest.public_.tables;


import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.epam.contest.public_.Keys;
import org.jooq.epam.contest.public_.Public;
import org.jooq.epam.contest.public_.tables.records.DescriptionRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Description extends TableImpl<DescriptionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.description</code>
     */
    public static final Description DESCRIPTION = new Description();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DescriptionRecord> getRecordType() {
        return DescriptionRecord.class;
    }

    /**
     * The column <code>public.description.id</code>.
     */
    public final TableField<DescriptionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.description.product_id</code>.
     */
    public final TableField<DescriptionRecord, Integer> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.description.descr</code>.
     */
    public final TableField<DescriptionRecord, Integer> DESCR = createField(DSL.name("descr"), SQLDataType.INTEGER.nullable(false), this, "");

    private Description(Name alias, Table<DescriptionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Description(Name alias, Table<DescriptionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.description</code> table reference
     */
    public Description(String alias) {
        this(DSL.name(alias), DESCRIPTION);
    }

    /**
     * Create an aliased <code>public.description</code> table reference
     */
    public Description(Name alias) {
        this(alias, DESCRIPTION);
    }

    /**
     * Create a <code>public.description</code> table reference
     */
    public Description() {
        this(DSL.name("description"), null);
    }

    public <O extends Record> Description(Table<O> child, ForeignKey<O, DescriptionRecord> key) {
        super(child, key, DESCRIPTION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DescriptionRecord, Long> getIdentity() {
        return (Identity<DescriptionRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DescriptionRecord> getPrimaryKey() {
        return Keys.DESCRIPTION_PKEY;
    }

    @Override
    public Description as(String alias) {
        return new Description(DSL.name(alias), this);
    }

    @Override
    public Description as(Name alias) {
        return new Description(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Description rename(String name) {
        return new Description(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Description rename(Name name) {
        return new Description(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
